[package]
name = "anycase"
version = "0.0.0"
authors = ["Ross MacArthur <ross@macarthur.io>"]
edition = "2018"
rust-version = "1.56.0"
description = "a case conversion library for Rust"
readme = "README.md"
repository = "github.com/rossmacarthur/anycase"
license = "MIT OR Apache-2.0"
keywords = ["case", "snake", "camel", "pascal", "unicode"]
categories = ["text-processing", "no-std"]
include = ["src/**/*", "README.md"]

[features]
default = ["alloc"]
alloc = []

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
