[badges]
github_workflow = { label = "build", name = "rust" }

[links]
"crate::raw" = "https://doc.rs/anycase/latest/anycase/raw/index.html"
"char::is_alphanumeric" = "https://doc.rust-lang.org/stable/core/primitive.char.html#method.is_alphanumeric"
"char::is_lowercase" = "https://doc.rust-lang.org/stable/core/primitive.char.html#method.is_lowercase"
"char::is_uppercase" = "https://doc.rust-lang.org/stable/core/primitive.char.html#method.is_uppercase"
"as_camel" = "https://docs.rs/anycase/latest/anycase/fn.as_camel.html"
"as_pascal" = "https://docs.rs/anycase/latest/anycase/fn.as_pascal.html"
"as_snake" = "https://docs.rs/anycase/latest/anycase/fn.as_snake.html"
"as_screaming_snake" = "https://docs.rs/anycase/latest/anycase/fn.as_screaming_snake.html"
"as_kebab" = "https://docs.rs/anycase/latest/anycase/fn.as_kebab.html"
"as_screaming_kebab" = "https://docs.rs/anycase/latest/anycase/fn.as_screaming_kebab.html"
"as_train" = "https://docs.rs/anycase/latest/anycase/fn.as_train.html"
"as_lower" = "https://docs.rs/anycase/latest/anycase/fn.as_lower.html"
"as_title" = "https://docs.rs/anycase/latest/anycase/fn.as_title.html"
"as_upper" = "https://docs.rs/anycase/latest/anycase/fn.as_upper.html"
